### ISSUE TITLE
Swap: Invalid input values should be corrected

### ISSUE THREAD

**Issue by samoslag** [reef-defi/reef-react-lib#128]
Value placed in input should be validated and corrected on input blur.
!Important: Inputs for both tokens must be validated when value in any one of them is changed.

![Untitled-3](https://user-images.githubusercontent.com/59774151/185760517-92fa4033-9d76-42b4-b434-ecaaca0aa884.jpg)
![Untitled-4](https://user-images.githubusercontent.com/59774151/185760518-05fa781d-2d9c-469e-8fd6-a0802d1c26ef.jpg)

**Comment by samoslag** [comment]
There's an issue with rate as well...
![Untitled-1](https://user-images.githubusercontent.com/59774151/188622701-ee82a9a6-9695-4d1f-a897-407628305459.jpg)

**Comment by Frenkiee** [comment]
This is ok. The rate is calculated based on pool reserves and the given amount goes through intermediate calculus that "readjusts" the output rate  (calc is used from the contract)
